### ISSUE TITLE
Prisma subscriptions example

### ISSUE THREAD

**Issue by hoodsy** [graphcool/prisma#1671]
**Current behavior**

Firing a mutation in the subscriptions example throws the error: `[Network error]: FetchError: request to http://localhost:60000/subscriptions/dev failed, reason: connect ECONNREFUSED 127.0.0.1:60000`

Changing the Prisma endpoint being supplied to `graphql-yoga` to `'http://localhost:4466/subscriptions/test'` resolves this error.

Without any errors, listening on the `publications` subscription and firing `writePost` doesn't trigger any subscription events.

**Comment by marktani** [comment]
Hey @hoodsy, thanks a lot for your feedback!
This is a problem with the hardcoded endpoint here (in `src/index.js`):

```
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: 'src/generated/prisma.graphql',
      endpoint: 'http://localhost:60000/subscriptions/dev',
      secret: 'mysecret123',
    }),
    debug: true,
  }),
})
```

Could you please replace that with

```
endpoint: 'http://localhost:4466/subscriptions/test'
```

Clearly the README should be adjusted accordingly 🙂

**Comment by hoodsy** [comment]
The `graphql-yoga/subscriptions` example has a working implementation using `PubSub`: https://github.com/graphcool/graphql-yoga/tree/master/examples/subscriptions

**Comment by marktani** [comment]
Yesterday we released a new minor version that fixed a specific bug with subscriptions, could you try upgrading? :slightly_smiling_face: `npm install - g prisma` `prisma local upgrade`

**Comment by hoodsy** [comment]
Thanks for the heads up – I've upgraded, but am still getting the same results. `Message` subscription is active, but creating a `Message` doesn't trigger the subscription:

**Subscription**
```gql
subscription ($_where: MessageSubscriptionWhereInput) {
  message(where: $_where) {
    node {
      text
      sender {
        id
        name
      }
    }
  }
}
variables:
{
  "_where": {
    "mutation_in": [
      "CREATED",
      "UPDATED"
    ]
  }
}
```

**Mutation**
```gql
mutation ($data: MessageCreateInput!) {
  createMessage(data: $data) {
    id
    text
    sender {
      id
      name
      __typename
    }
    __typename
  }
}
operationName: null
variables:
{
  "data": {
    "text": "test"
  }
}
```

Same goes for the `prisma/examples/subscriptions` example... At the same time, the `graphql-yoga/subscriptions` example works, but doesn't depend on Type subscriptions. This is the only bit of subscription code I've been able to get running

**Comment by daver182** [comment]
I'm getting the same results, the subscription works but only when using the prisma endpoint, not with the node app. The response from the server is ok but I don't get any update, I've tested with the example and all the tools on the latest version

**Comment by oxy88** [comment]
Same.
Subscription works only with prisma, doesn't works on app.
I've tried with official subscription examples, Air bnb examples and howtographql examples on my Mac and Linux machine both didn't work

**Comment by marktani** [comment]
[A recent change](https://github.com/graphcool/prisma-binding/commit/2117ddffdad990867616505ef80f618e4628a21d) in `prisma-binding` might be related, could you try it with version `1.4.0` again, @hoodsy @daver182? 🙂 

The authorization token was not passed into the subscription link.

**Comment by hoodsy** [comment]
In the playground, where subscriptions work, I am required to use the subscription `message`: 

```gql
subscription {
  message {
       node {
         id
         text
       }
     }
  }
```

In my app, the `message` subscription throws an error, and requires I use `messages`, but doesn't pick up any newly created messages.

**Comment by marktani** [comment]
@hoodsy, can you share more information about this?

What is the error you receive when using `message`? How are you setting up the `message` subscription in your code? How does your `schema.graphql` look like?

**Comment by hoodsy** [comment]
I've realized the error with `message` is schema related – with all naming aligned and no errors, I don't have subscriptions coming through in app (but do in playground with same query):

```gql
# in UI
const MESSAGES_SUBSCRIPTION = gql`
  subscription message {
    message {
      node {
        text
        sender {
          id
          name
        }
      }
    }
  }
`
```

```js
// in resolvers/index.js
  Subscription: {
    message: {
      subscribe: async (parent, args, ctx, info) => {
        return ctx.db.subscription.message({
            where: {
              mutation_in: ['CREATED', 'UPDATED'],
            },
          }, info)
      },
    },
```

```gql
# in schema.graphql
type Subscription {
  message: MessageSubscriptionPayload
}
```

**Comment by daver182** [comment]
@marktani no, it's not that, I've tried with the example

**Comment by marktani** [comment]
Hey @hoodsy and @daver182, thanks a lot for your help with this. I could single out the problem, fixed the subscription example for now, and created a new bug report here: https://github.com/graphcool/prisma/issues/1734

It seems that subscriptions don't always work when `where` is used. 

@hoodsy you should be able to confirm this by changing your subscription resolver to

```js
// in resolvers/index.js
  Subscription: {
    message: {
      subscribe: async (parent, args, ctx, info) => {
        return ctx.db.subscription.message({ }, info)
      },
    },
```

Please follow the discussion in the new issue, thanks 🙌
