### ISSUE TITLE
Inconsistencies in the generated schema  for self-relations and optional back relations 

### ISSUE THREAD

**Issue by do4gr** [graphcool/prisma#1966]
Using the following schema there are a couple of bugs and inconsistencies caused in the validation of the schema and the generation of the API. 

```graphql
type User{
   name: String! @unique
   friends: [User!]!  @relation(name: "UserFriends")
   friendOf: [User!]! @relation(name: "UserFriends")
   bestFriend: User   @relation(name: "BestFriend")
   bestFriendOf: User @relation(name: "BestFriend")
   bestBuddy: User
}
```

The schema validator does not allow a schema like this at the moment although the relations are unambigous. 

Due to this being a self-relation `UserCreateManyWithoutFriendOfInput ` does not contain the correct create input type. 
```graphql
input UserCreateManyWithoutFriendOfInput {                              
  create: [UserCreateWithoutFriendsInput!]                                  
  connect: [UserWhereUniqueInput!]
}

input UserCreateManyWithoutFriendsInput {
  create: [UserCreateWithoutFriendsInput!]
  connect: [UserWhereUniqueInput!]
}
```
The self-relation problems also appear on schemata that we allow at the moment. 

The input type for bestBuddy is also not correct. It should contain the BestFriend field.
```graphql
input UserCreateInput {
  name: String!
  friends: UserCreateManyWithoutFriendOfInput
  friendOf: UserCreateManyWithoutFriendsInput
  bestFriend: UserCreateOneWithoutBestFriendOfInput
  bestFriendOf: UserCreateOneWithoutBestFriendInput
  bestBuddy: UserCreateOneWithoutBestFriendInput
}
```

**Comment by mvaivre** [comment]
I was going to create an issue for this: https://www.graph.cool/forum/t/inconsistencies-with-self-relations/2593/3 but it seems you outlined the same problem here, thanks!
Those inconsistencies are totally breaking my API and are preventing me from going to production, so if you think I can help in any way (test etc..) don't hesitate to ping me!

**Comment by do4gr** [comment]
Hey @mvaivre, I hope to be able to tackle this issue towards the end of this week. I'll let you know once it is in the unstable channel and then you can test it with your project before we release it.

**Comment by mvaivre** [comment]
That would be awesome @do4gr, good luck and thanks a lot.

**Comment by marktani** [comment]
This is now fixed and available in `1.4.0` 🙂Thanks a lot for your feedback, @mvaivre 💚

**Comment by AlexanderChen1989** [comment]
```graphql 
# model
type User {
  id: ID! @unique
  name: String! @unique
  children: [User!]!
}

mutation {
  createUser(
    data: {
      name: "A"
      children: {
        create: [{ name: "B", children: { create: [{ name: "C" }] } }]
      }
    }
  ) {
    id
    children {
      id
      children {
        id
        children {
          id
        }
      }
    }
  }
}

```
with prism 1.4.0, I still cant create User "C"
![image](https://user-images.githubusercontent.com/2957936/37386528-c33b9850-2793-11e8-9d95-a2610989bc73.png)

**Comment by marktani** [comment]
Hey Alexander, as far as I understand your situation, you need to use two fields, `parent: User @relation(name: "Users")` and `children: [User!]! @relation(name: "Users)`.

If that still doesn't work, please start a discussion about your problem in a new issue 🙂

**Comment by AlexanderChen1989** [comment]
still  not work
I changed model to 
```graphql
type User {
  id: ID! @unique
  name: String! @unique
  parent: User @relation(name: "Users")
  children: [User!]! @relation(name: "Users")
}
```

**Comment by marktani** [comment]
Thanks, please start a discussion about your problem in a new issue 🙂
