### ISSUE TITLE
Syntax Error: Expected Name, found }

### ISSUE THREAD

**Issue by canercandan** [graphcool/prisma#1981]
# Bug Report

**Current behavior**

```gql
type Breed {
  id: ID! @unique
  animals: [Animal!]! 
}

type Animal {
  id: ID! @unique
  name: String!
  breed: Breed!
}
```

If one of your type has a relation with another one that does not contain anything else than an `id` and relational fields, the `prisma deploy` command will end up with the error:

```bash
Syntax Error: Expected Name, found }
```

Prisma version:

```bash
$ prisma --version
prisma/1.2.8 (linux-x64) node-v8.7.0
```

Adding a dummy string-typed field fixes the issue:

```diff
type Breed {
  id: ID! @unique
  animals: [Animal!]! 
+ dummy: String
}
```

**Comment by mzygmunt** [comment]
Same in version Prisma 1.3.0

**Comment by marktani** [comment]
When creating a datamodel that incudes types without scalar fields, a schema with empty input types is generated. This is a problem for graphql-js 0.11. graphql 0.12 & 0.13 can print this schema without problems. However, parsing the printed schema again results in this error.

Note that older versions of `graphql-js` throw a different error, described in #1817.

The fix here is that the backend should not generate empty input types. We're tackling that soon 🙂

**Comment by marktani** [comment]
This is now fixed and available in `1.4.0` 🙂

**Comment by sergio91pt** [comment]
I'm still having this issue on newly created projects, with prisma 1.4.1.

To replicate I created a new node-basic project with graphql-cli.
Adding this to `database/datamodel.graphql` and running `yarn prisma deploy` triggers the error:
```gql
type Root {
  value: TypeA
}

type TypeA {
  dummy: String
}
```

**Comment by Evilweed** [comment]
Still occurs on latest Prisma...

**Comment by marktani** [comment]
Hey @Evilweed, in the original issue, this error occured when running `prisma deploy`.

I just tried to deploy the data model you shared, and it worked without a problem. From what you shared with us so far, it's not clear what happens when you run `yarn start`.

Please create a new issue, including the information what happens when you run `yarn start` and a minimal reproduction. Thanks! 🙂

**Comment by marktani** [comment]
@sergio91pt, I could reproduce the problem you describe.

Changing `Root` to this is a working work around:

```
type Root {
  id: ID! @unique
  value: TypeA
}
```

**Comment by marktani** [comment]
I cannot reproduce this on the latest version `1.6.3`.
If you still run into a problem, please provide a full reproduction in a _new_ issue report 🙂
Thanks 🙌
