### ISSUE TITLE
Import fails with exceeding size reason.

### ISSUE THREAD

**Issue by donedgardo** [graphcool/prisma#2024]
# Bug Report

**Current behavior**
Running `prisma import -d export-2018-03-06T04:48:12.466Z.zip -e .env.prod` doesnt complete import instead debugs witha exceeding size exeption:
```bash
Unzipping... 225ms

Validating data... 540ms

Uploading nodes...
  client Uploading to endpoint https://us1.prisma.sh/edgardo-carreras/beaconsofhope-prisma/prod/import +0ms
Error: The request content was malformed:
EntityStreamSizeException: actual entity size (Some(10049921)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
    at Client.<anonymous> (/Users/donedgardo/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/prisma-cli-engine/src/Client/Client.ts:321:13)
    at step (/Users/donedgardo/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/prisma-cli-engine/dist/Client/Client.js:32:23)
    at Object.next (/Users/donedgardo/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/prisma-cli-engine/dist/Client/Client.js:13:53)
    at fulfilled (/Users/donedgardo/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/prisma-cli-engine/dist/Client/Client.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```
![screen shot 2018-03-06 at 12 53 06 am](https://user-images.githubusercontent.com/2483536/37014750-1bef01c4-20d9-11e8-806d-45e513eaebf0.png)

**Expected behavior?**
Successful import or better description of how to configure service to skip size limit.

**Comment by marktani** [comment]
Thanks for the report @donedgardo, we're looking into this soon 🙂

**Comment by donedgardo** [comment]
https://github.com/graphcool/prisma/blob/c77e582b5fd6edc62d18bb03d060f5f2d3d2172a/server/servers/api/src/main/resources/application.conf#L18 @do4gr

**Comment by horsejockey** [comment]
@donedgardo were you able to find any kind of workaround for this?

**Comment by donedgardo** [comment]
I haven’t. Dont know how to build  scala with different configurations

**Comment by horsejockey** [comment]
@donedgardo I wrote this python script that uses the api to do the migration.  Takes a long time cause the python requests library was giving me trouble when I sent to much data so I had to sub-batch it during import.
https://gist.github.com/horsejockey/54748992ac98ae92d0a6f05480750e0c

**Comment by johhansantana** [comment]
Tried the fix in unstable channel `beta` locally
v1.5.0-beta.1

Got the following error:
```
Uploading nodes...
  client Uploading to endpoint http://localhost:4466/<my-project-name>/dev/import +0ms
FetchError: request to http://localhost:4466/<my-project-name>/dev/import failed, reason: socket hang up
```

@do4gr

**Comment by do4gr** [comment]
Hey, @johhansantana,

thanks for quickly testing it!

I am still working on this issue even though the PR closed it. Enabling the import of larger file sizes exposed some performance problems that I am cleaning up at the moment. Your error is a symptom of this. I'll post again once I feel the issue is solved.

**Comment by giapnhtadi** [comment]
@do4gr  This issue was fixed or not? I got same issue, so please don't close the task when it is not fixed yet.

**Comment by marktani** [comment]
Hey @giapnhtadi,

this fix is available already on [the unstable channel](https://github.com/graphcool/prisma/wiki/Release-Channels#running-the-unstable-channel).

It will be rolled out to the development clusters with the next point release, and will then also be available on private clusters.

If you're running this locally, can you confirm that you run against a cluster with a version that contains `1.5.0-beta`?

**Comment by johhansantana** [comment]
I think what @giapnhtadi meant is that the issue is not really fixed because you can't import a backup yet successfully, even in the unstable channel.

**Comment by marktani** [comment]
Hey @donedgardo @johhansantana @giapnhtadi, [this PR](https://github.com/graphcool/prisma/pull/2120) includes a fix for the problems you observes, as well as performance improvements. It is available on the latest beta. I would love to hear your feedback about it :slightly_smiling_face:

**Comment by marktani** [comment]
I'm so sorry, I mixed it up :see_no_evil: https://github.com/graphcool/prisma/pull/2115 is the PR in question, and it's still open. We'll merge it soon, and I will notify you then.

**Comment by johhansantana** [comment]
@marktani Weird thing is that I tried today again to do the import locally and it worked this time. I took a few minutes to complete but the manual import worked.

Not sure if there's anything that has been changed since my last attempt though. Can anyone else confirm?

**Comment by do4gr** [comment]
@johhansantana The import was sometimes failing due to using too much of the JVM's memory. So it was not entirely predictable when or if it would fail. If you had enough free memory before and were not doing anything else with your server it might have gone through even before the changes. The last PR includes an almost complete rework of import to use less memory. It also should speed up the import noticeably so you do not get a timeout response from the CLI that you might've gotten before if the server takes more than 300 seconds to import one 10mb chunk.

**Comment by do4gr** [comment]
The fix is now rolled out.
